In [1]:
import numpy as np

In [17]:
np.random.random(2)

array([0.20445225, 0.87811744])

In [14]:
np.random.randint(0, 10, 10)

array([0, 1, 7, 6, 9, 2, 4, 5, 2, 4], dtype=int32)

In [22]:
np.random.sample(10)

array([0.31551563, 0.68650093, 0.83462567, 0.01828828, 0.75014431,
       0.98886109, 0.74816565, 0.28044399, 0.78927933, 0.10322601])

In [26]:
a = np.array([1, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([10, 30, 40, 50, 60, 70, 80, 90, 100])

# len(a), len(b)

np.dot(a, b)

np.int64(3810)

In [30]:
# sum(np.array([10, 30, 40, 50, 60, 70, 80, 90, 100]))* sum(np.array([1, 3, 4, 5, 6, 7, 8, 9, 10]))

np.int64(28090)

In [35]:
a = np.array([[1, 3, 4], [5, 6, 7], [8, 9, 10]])
a.ndim
np.linalg.inv(a)

array([[-1.        ,  2.        , -1.        ],
       [ 2.        , -7.33333333,  4.33333333],
       [-1.        ,  5.        , -3.        ]])

In [37]:
a = np.array([[1, 2], 
                            [2, 1]])
np.linalg.inv(a)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [38]:
np.linalg.diagonal(a)

array([1, 1])

In [40]:
np.linalg.eigh(a)

EighResult(eigenvalues=array([-1.,  3.]), eigenvectors=array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]]))

In [48]:
np.matrix(a)

matrix([[1, 2],
        [2, 1]])

In [50]:
np.linspace(start=10, stop=20, num=15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])